title: Tiliki Faith Ejiroghene
logo: Faith.jpg
description: A Data Analyst with three years experience using microsoft excel for data analysis and visualization, sql for data interrogation and manipulation and microsoft powerbi for creating business intelligence report.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
